# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

category:
  url:      /category/:slug
  class:    sfPropelRoute
  param:    { module: category, action: show }
  options:  { model: JobeetCategory, type: object }

job_show_user:
  url:     /job/:company_slug/:location_slug/:id/:position_slug
  class:   sfPropelRoute
  options:
    model: JobeetJob
    type:  object
    method_for_criteria: doSelectActive
  param:   { module: job, action: show }
  requirements:
    id: \d+
    sf_method: [GET]



# default rules
homepage:
  url:   /
  param: { module: default, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*


# NOTAS
# url_for('@default?module=job&action=show&id='.$job->getId()) ---------------> PARA GENERAR LA RUTA AUTOMATICA
# requirements ----------> Se pueden validar variables con regEx
# class: sfRequestRout + requirements: sf_method: [metodo http] --------------> VALIDA EL METODO, SI NO COINCIDE CONTINUA
