<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2021/05/04 19:12:12
sfConfig::add(array(
  'app_active_days' => 30,
  'app_max_jobs_on_homepage' => 10,
  'app_max_jobs_on_category' => 20,
));
